### ISSUE TITLE
pow_workaround  error for demo.R

### ISSUE THREAD

**Issue by cbud** [jannebor/pow_workaround#1]
Hi

I am trying to get your pow_workaround code to work but get

Error in html(paste("http://plantsoftheworldonline.org/taxon/", ppow[1], : 
could not find function "html"

which is at line 35 of the demo.R file.

I wondered if a package was missing and tried library(htmltools)...

We are looking at native ranges of invasive species...

Hopefully

Chris

**Comment by jannebor** [comment]
Hi Chris, thanks for letting me know. There was indeed a dependency requiring some updates. It should be fixed now, but let me know if it still doesn't work!
